### ISSUE TITLE
ValueYourTime

### ISSUE THREAD

**Issue by CKone2k** [CKone2k/CK-capstone#1]
### Value proposition

As a user
I want to reach goals and manage my time more efficient
in order to achieve things otherwise too time-consuming to do in a normal day.
### Description
<img width="311" alt="Screenshot 2023-04-24 at 11 03 58" src="https://user-images.githubusercontent.com/125925578/233950636-63e2021d-d891-4750-a482-ed8b68920e88.png">

### Acceptance Criteria
- Goals are shown
- Username is displayed
- Goals are displayed as tags
- set time is displayed 

### Task 

1. create form
2. create object from submit

Size M

**Comment by mulewile** [comment]
You might still have to update the value proposition. I left a comment in your initial user story.

**Comment by BenRodProd** [comment]
It looks like the user wants to manage other peoples time... is that your plan? if not, the value proposition should be smth like "As a user, I want to use my time more efficiently" 
And in the Tasks, instead of "create activities of your goals" and "set time when to remind" i would go for smth. like: 
- create Dummy Data for Activities and time
- display dummy data as a list

smth like that...
